security:
   
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # Zone publique pour le Login (gérée par le bundle ou ta route dédiée)
        # Si ta route de login n'utilise pas le guard classique, le firewall 'api' s'en chargera.
        
        api:
            pattern: ^/api
            stateless: true
            # block_listeners permet d'éviter que le décodeur JWT bloque les requêtes anonymes
            jwt: ~
            # On indique à Symfony que les utilisateurs anonymes sont tolérés au niveau du pare-feu
            # L'access_control prendra ensuite le relais pour restreindre ou non
            required_badges: [] 

    access_control:
        # 1. Routes totalement publiques (Visiteurs)
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/utilisateur/inscription, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/salle/getAllRooms, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/salle/get_one/\d+, methods: [GET], roles: PUBLIC_ACCESS }
        
        # 2. Verrou global : Tout le reste (y compris get_all, delete, me...) demande une authentification
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10